### ISSUE TITLE
Quiet/muffled audio feed from Game board to Music

### ISSUE THREAD

**Issue by zomgugoff** [vipoo/yellow-msx-series-for-rc2014#12]
I've been running then audio from the Game and Music boards to an external mixer and noticed the volumes are very different. Reading around, this is known behavior of the hardware. But, running audio between the boards with jumpers, I noticed the input audio is even lower and the high-end is seemingly cut off, making it sound muffled. I was able to bypass this filtering by jumping directly to the leg of the component before it enters the jack on the Music board.

Is the filtering and quieting intentional? I could see that being present in original hardware, but it seems like the sort of thing that would be left out as it was detracting from audio quality.

**Comment by vipoo** [comment]
Yes - I initially tried to align with original designs.  The Music Module has gone through a number of iterations to try and improve the signal-to-noise ratio and audio balance.  

I am not sure what version you have (you can tell by looking at the back of the PCB).

Recent changes include 'increasing' the gain of the Music Module - and some tweaks to the filter caps to increase the roll off frequency a bit.  

* https://github.com/vipoo/yellow-msx-series-for-rc2014/blob/main/music/README.md#changes-for-v19
* https://hackaday.io/project/175574-msx-compatible-boards-for-rc2014/log/230345-art-is-never-finished

> My audio/analogue design skills/knowledge is certainly stretch to the limit

**Comment by zomgugoff** [comment]
I see. I have a v1.9 board. Good luck with finding the balance. Considering the varied volume output of the FM chip (I switched to a AY-3-8910 because the volume is higher), it might be worth installing a pot to allow user adjustment of the header feed.
