### ISSUE TITLE
Use correct Omega Home Computer reference

### ISSUE THREAD

**Issue by skiselev** [vipoo/yellow-msx-series-for-rc2014#5]
In the Acknowledgements, please use "Omega Home Computer Project" instead of "The Omega MSX Kit"

- I never offered a kit (although some other people or companies may have)
- MSX is a registered trademark. I don't use it in the name of the project (I am not a lawyer, but I wouldn't recommend using it in other projects names either, it should be OK to say "MSX" compatible though)

Thanks

**Comment by vipoo** [comment]
Hi Mate,

Thanks for the feedback and corrections - on it now
